### ISSUE TITLE
Some crashtest of Crash me Now! doesn't crash application!

### ISSUE THREAD

**Issue by xabolcs** [mozilla/nightlytt#117]
For example **ObjC Exception!** crashes only under Mac OS X by definition.

See original [Bug 837540](https://bugzilla.mozilla.org/show_bug.cgi?id=837540)!

My propose is to hide those menuitems.

**Comment by UtiluMark** [comment]
On Windows 10, the last three Crashme options (listed below) do not cause a crash:
1. "Pure virtual call!"
2. "Invalid parameter to CRT method!"
3. "ObjC Exception!"
Quite a few changes have been made in the Crashme extension in the meantime:
https://github.com/luser/crashme/commits/master

**Comment by whimboo** [comment]
I would say lets upgrade to the newest release then! :)

**Comment by tonymec** [comment]
Just FYI, I don't feel much concerned since on Linux where I am, a bogus crash can be triggered with no need for an extension, by means of the "kill" utility which sends the program an arbitrary signal. "kill -4" (SIGILL = illegal operation code) has my preference as something that is almost never seen as the result of a bug, but "kill -11" (SIGSEGV = segment boundary violation) will also trigger the crash reporter. The latter is a common signal of using an uninitialized or already-freed pointer, however. In any case a "user comment" should of course be typed in the crash reporter dialog to say that this crash was artificial.

**Comment by whimboo** [comment]
This issue was about the old version of crash me. The new one only supports a single type of crash for chrome and content. So this is not a problem anymore.
