### ISSUE TITLE
Port back code-changes from Utilu Nightly Tester Tools 3.7.1.1

### ISSUE THREAD

**Issue by whimboo** [mozilla/nightlytt#188]
Similar to PR #186 this issue keeps track of the work for porting back all the changes as done in Utilu Nightly Tester Tools 3.7.1.1. @UtiluMark will work on it.

**Comment by UtiluMark** [comment]
@whimboo What do you want to be the next change for me to port back in a new PR?

**Comment by whimboo** [comment]
I think all the customize titlebar changes would be nice to have next.

@xabolcs what do you think about removing partially translated locales? I don't think it's a good idea and we might better get in contact with the contributors who originally provided those locales. @UtiluMark which locales would be affected by this?

**Comment by xabolcs** [comment]
I agree with you @whimboo.

A new issue for updating locales would be good, but first land all functional changes and leave the string update at last.

**Comment by whimboo** [comment]
Sounds perfect to me. @UtiluMark once you finished with the parts of my last comment, lets re-list all the remaining issues in a new comment. That way we can get an overview what's left to do.

**Comment by UtiluMark** [comment]
@xabolcs I agree, all translations will be outdated because of the added customize titlebar options, so let's leave the translations as they are, until everything else is finished.

@whimboo I've just created PRs for the smaller changes. Once these are out of the way, I can start working at the large PR with all the customize titlebar changes.

I have a question about the customize titlebar changes, because I changed the default title.
Old: pref("nightly.templates.title", "${DefaultTitle} (Build ${AppBuildID})");
New: pref("nightly.templates.titlebar", "${TabTitle} - ${Vendor} ${Name} ${VersionChannel} (${AppBuildID})");
I changed "nightly.templates.title" to "nightly.templates.titlebar" so the new default would be used automatically.
I changed "${DefaultTitle} (Build ${AppBuildID})" to "${TabTitle} - ${Vendor} ${Name} ${VersionChannel} (${AppBuildID})" so more information is displayed in the titlebar.
Old: "Nightly Start Page - Nightly (Build 20151001030236)"
New: "Nightly Start Page - Mozilla Firefox 44.0.0.0 Nightly (20151001030236)"

Do you want me to only add the new customize titlebar options (which will be unused by default then), or also change the default title (so the new options are used by default like described above)?

**Comment by xabolcs** [comment]
I vote against changing default templates. Additions are welcome.

@UtiluMark, I saw in your original PR you transformed Nightly Tester Tools into Utilu Nightly Tester Tools. It's OK to do that as a forked extension in your (corporate) account, but don't want to merge those changes back into this repository.

As you rename it and give it a new UUID it would be a whole new extension.
Feel free to do it, and merge into Utilu account those changes, and please reference back to Mozilla as Utilu's NTT is a fork of Mozila's Nightly Tester Tools.

**Comment by whimboo** [comment]
@UtiluMark best you add a comment to each of those PRs and include @whimboo, so that I also get an email for them. Otherwise I won't notice them for a while.

As @xabolcs said, lets add the new variables but leave the default template as it is. You can change the latter in your fork instead.

**Comment by UtiluMark** [comment]
@whimboo Thanks, I've just done so in PR #191 #192 #193 #194 #195 and #196. 

After that I will start the large PR with the additional customize titlebar options, without changing the defaults.

**Comment by whimboo** [comment]
Thanks! @xabolcs if you have the time and want to review PRs please do so. Otherwise I will go through them tomorrow morning.

**Comment by UtiluMark** [comment]
@xabolcs I removed the copy to Pastebin functionality which had become non-working due to API changes, and replaced the non-working copy to Pastebin functionality by copy text to Clipboard functionality ("Copy about:support to Clipboard"). Is this a desired change or not? Because in issue #86 you wrote on 9 Feb 2014 that the development channel had a fix which uses pastebin.mozilla.org instead pastebin.com (PR #93). If that fix works, that might be the preferable solution compared to removing the Pastebin functionality entirely.

**Comment by xabolcs** [comment]
@UtiluMark, the fix in PR #93 does work, just need to be finished. No need to remove it for now. 
Thanks!

**Comment by UtiluMark** [comment]
@whimboo Could you take a look at PR #195, #196 and #198?

**Comment by UtiluMark** [comment]
@xabolcs It's good that the Pastebin functionality will get fixed. I had replaced the non-working copy to Pastebin functionality by copy text to Clipboard functionality ("Copy about:support to Clipboard"). Now that the Pastebin functionality will get fixed: shall I turn the Copy about:support to Clipboard option into an additional option (besides to the Pastebin option), or shall I remove it?

**Comment by xabolcs** [comment]
> Now that the Pastebin functionality will get fixed: shall I turn the Copy about:support to Clipboard option into an additional option (besides to the Pastebin option), or shall I remove it?

It's OK to me to keep both item in the menu! @whimboo, do you have any thoughts?

**Comment by whimboo** [comment]
Sounds good to me. When we do that lets add the new option at the place where the pastebin one is located at right now. The pastbin entry should then be separated with a line.

**Comment by xabolcs** [comment]
PR #196 landed.

**Comment by whimboo** [comment]
PR #195 landed too. @UtiluMark, is everything done now for this issue or do we still miss a part?

**Comment by UtiluMark** [comment]
@whimboo Like I said before https://github.com/mozilla/nightlytt/issues/188#issuecomment-145575689 I'm going to work on a new large PR with the additional customize titlebar options, without changing the defaults. This will also involve adding strings to all translation files.

**Comment by whimboo** [comment]
That comment was a while ago. So thanks for the update on that.

**Comment by UtiluMark** [comment]
@whimboo I've finished the new large PR with the additional customize title bar options: #212 
Since one of the added customize title bar options is the Beta Revision, this also fixes #204

**Comment by whimboo** [comment]
The rewrite of the extension is now in beta state, and the left-overs from this issue won't be worked on anymore because it would only affect the old and legacy extension.
