### ISSUE TITLE
Revert "Copy extensions to clipboard" to use new lines as separator by default

### ISSUE THREAD

**Issue by whimboo** [mozilla/nightlytt#230]
From https://github.com/mozilla/nightlytt/pull/195#issuecomment-258186582.

With the change from new line to comma for separating extensions while copying them into the clipboard has been changed a behavior which users of the extensions were used to all the time. We should revert that to use new lines again. In a followup issue we can then make it configurable via the preferences screen or a hidden preference.

**Comment by whimboo** [comment]
Given that @UtiluMark didn't fix it yet, I will do the revert now.

**Comment by whimboo** [comment]
PR #237 landed for the 3.10 release.

**Comment by UtiluMark** [comment]
@whimboo The problem with #232 is that \n set as preference gets escaped and doesn't become a newline.

The problem with reverting is that issue #195 returns, as for example input fields don't support newlines, all extensions will get glued together. In #232 this is fixed by detecting this and using a comma instead of a non working new line (which means no separator) in that case.

**Comment by whimboo** [comment]
Doh. Looks like we missed that indeed. So it should be fine when we leave the comma separated list for pasting into text fields, and keep the backslash for the clipboard. That way we can close the regression for external usage, and make it easier for handling this list inside of Firefox when directly pasting it into textboxes.

Does that sound fine?

**Comment by UtiluMark** [comment]
@whimboo Yes, that sounds fine and that's how this is fixed in PR #232: by default only in case of input fields a comma is used (because input field don't support newlines and all extensions would get glued together), in all other cases (textarea, copy to clipboard for external usage) new lines are used.
```
if (type == "input") {
        var extensionSeparator = ", ";
      } else {
        var extensionSeparator = "\n";
}
```

**Comment by whimboo** [comment]
I reverted the changes as pushed by backing out the changeset:
https://github.com/mozilla/nightlytt/commit/7cd79e2fda4db042edc3b49a6a1179323bd2f225

I will have a new PR in a moment.

**Comment by whimboo** [comment]
PR #240 got merged and fixed the remaining issue @UtiluMark pointed out. Thanks for that!
